import type { Organization, Activity, SystemService } from "./types";

export const MOCK_ORGS: Organization[] = [
  {
    id: "tracebuild-default",
    name: "TraceBuild",
    planTier: "enterprise",
    status: "active",
    createdAt: "2024-01-15T08:00:00Z",
    isDefault: true,
    description: "Internes TraceBuild-Konto",
    owner: "Jonas Jud",
    ownerEmail: "jonas@tracebuild.ch",
    userCount: 4,
    projectCount: 12,
    analyseCount: 147,
    storageGB: 3.2,
    monthlyBudget: 500,
  },
  {
    id: "org-mueller",
    name: "Müller Architekten AG",
    planTier: "pro",
    status: "active",
    createdAt: "2024-03-10T09:00:00Z",
    description: "Architekturbüro in Zürich",
    owner: "Stefan Müller",
    ownerEmail: "s.mueller@mueller-arch.ch",
    userCount: 8,
    projectCount: 23,
    analyseCount: 312,
    storageGB: 7.8,
    monthlyBudget: 400,
  },
  {
    id: "org-hochbau-zh",
    name: "Hochbauamt Kanton ZH",
    planTier: "enterprise",
    status: "active",
    createdAt: "2024-05-22T10:00:00Z",
    description: "Kantonale Bauverwaltung Zürich",
    owner: "Dr. Sandra Brunner",
    ownerEmail: "s.brunner@hochbau.zh.ch",
    userCount: 15,
    projectCount: 41,
    analyseCount: 589,
    storageGB: 18.4,
    monthlyBudget: 1200,
  },
  {
    id: "org-design-bau",
    name: "DesignBau Studio",
    planTier: "starter",
    status: "paused",
    createdAt: "2024-09-01T11:00:00Z",
    description: "Kleines Designbüro, Nutzung pausiert",
    owner: "Luca Ferretti",
    ownerEmail: "l.ferretti@designbau.ch",
    userCount: 2,
    projectCount: 3,
    analyseCount: 18,
    storageGB: 0.4,
    monthlyBudget: 150,
  },
  {
    id: "org-planungs-be",
    name: "Planungs AG Bern",
    planTier: "pro",
    status: "active",
    createdAt: "2024-11-15T08:30:00Z",
    description: "Planungsbüro Region Bern",
    owner: "Ursula Käser",
    ownerEmail: "u.kaeser@planungs-ag.ch",
    userCount: 6,
    projectCount: 17,
    analyseCount: 203,
    storageGB: 5.1,
    monthlyBudget: 350,
  },
  {
    id: "org-arch-koll",
    name: "Architektur Kollektiv",
    planTier: "starter",
    status: "closed",
    createdAt: "2024-07-01T10:00:00Z",
    description: "Konto geschlossen auf Kundenwunsch",
    owner: "Nina Schärli",
    ownerEmail: "n.schaerli@arch-koll.ch",
    userCount: 3,
    projectCount: 5,
    analyseCount: 42,
    storageGB: 0.9,
    monthlyBudget: 150,
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-001",
    type: "analyse_completed",
    orgName: "Hochbauamt Kanton ZH",
    orgId: "org-hochbau-zh",
    user: "Dr. Sandra Brunner",
    timestamp: "2026-07-28T10:30:00Z",
    meta: "Gebäude A — Grundriss EG",
  },
  {
    id: "act-002",
    type: "plan_uploaded",
    orgName: "Müller Architekten AG",
    orgId: "org-mueller",
    user: "Stefan Müller",
    timestamp: "2026-07-28T09:15:00Z",
    meta: "Schnitt B-B.pdf",
  },
  {
    id: "act-003",
    type: "analyse_started",
    orgName: "Planungs AG Bern",
    orgId: "org-planungs-be",
    user: "Ursula Käser",
    timestamp: "2026-07-27T16:45:00Z",
  },
  {
    id: "act-004",
    type: "report_created",
    orgName: "Hochbauamt Kanton ZH",
    orgId: "org-hochbau-zh",
    user: "Dr. Sandra Brunner",
    timestamp: "2026-07-27T14:20:00Z",
    meta: "Bericht Projekt Zolliker Str.",
  },
  {
    id: "act-005",
    type: "user_invited",
    orgName: "TraceBuild",
    orgId: "tracebuild-default",
    user: "Jonas Jud",
    timestamp: "2026-07-27T11:00:00Z",
    meta: "m.weber@tracebuild.ch",
  },
  {
    id: "act-006",
    type: "project_created",
    orgName: "Müller Architekten AG",
    orgId: "org-mueller",
    user: "Stefan Müller",
    timestamp: "2026-07-26T17:30:00Z",
    meta: "Neubau Wohnhaus Zürich-Enge",
  },
  {
    id: "act-007",
    type: "analyse_completed",
    orgName: "Planungs AG Bern",
    orgId: "org-planungs-be",
    user: "Ursula Käser",
    timestamp: "2026-07-26T13:10:00Z",
    meta: "Ansicht Süd — Ausführungsplan",
  },
  {
    id: "act-008",
    type: "plan_uploaded",
    orgName: "Hochbauamt Kanton ZH",
    orgId: "org-hochbau-zh",
    user: "M. Hofmann",
    timestamp: "2026-07-25T15:45:00Z",
    meta: "Grundriss OG — Revision 3.pdf",
  },
  {
    id: "act-009",
    type: "org_opened",
    orgName: "TraceBuild",
    orgId: "tracebuild-default",
    user: "Jonas Jud",
    timestamp: "2026-07-25T09:30:00Z",
  },
  {
    id: "act-010",
    type: "analyse_started",
    orgName: "Müller Architekten AG",
    orgId: "org-mueller",
    user: "K. Steiner",
    timestamp: "2026-07-24T16:20:00Z",
  },
  {
    id: "act-011",
    type: "plan_uploaded",
    orgName: "Planungs AG Bern",
    orgId: "org-planungs-be",
    user: "Ursula Käser",
    timestamp: "2026-07-24T11:00:00Z",
    meta: "Lageplan_final_v2.pdf",
  },
  {
    id: "act-012",
    type: "report_created",
    orgName: "Müller Architekten AG",
    orgId: "org-mueller",
    user: "Stefan Müller",
    timestamp: "2026-07-23T14:30:00Z",
    meta: "Prüfbericht Rüschlikon",
  },
  {
    id: "act-013",
    type: "org_edited",
    orgName: "DesignBau Studio",
    orgId: "org-design-bau",
    user: "Jonas Jud",
    timestamp: "2026-07-22T10:15:00Z",
  },
  {
    id: "act-014",
    type: "project_created",
    orgName: "Hochbauamt Kanton ZH",
    orgId: "org-hochbau-zh",
    user: "Dr. Sandra Brunner",
    timestamp: "2026-07-22T08:45:00Z",
    meta: "Schulhaus Erweiterung Winterthur",
  },
  {
    id: "act-015",
    type: "analyse_completed",
    orgName: "Hochbauamt Kanton ZH",
    orgId: "org-hochbau-zh",
    user: "M. Hofmann",
    timestamp: "2026-07-21T16:00:00Z",
    meta: "Brandschutzplan Rev. 2",
  },
  {
    id: "act-016",
    type: "cost_limit_reached",
    orgName: "DesignBau Studio",
    orgId: "org-design-bau",
    user: undefined,
    timestamp: "2026-07-21T12:30:00Z",
    meta: "Monatslimit CHF 150 erreicht",
  },
  {
    id: "act-017",
    type: "user_invited",
    orgName: "Müller Architekten AG",
    orgId: "org-mueller",
    user: "Stefan Müller",
    timestamp: "2026-07-20T15:00:00Z",
    meta: "p.brunner@mueller-arch.ch",
  },
  {
    id: "act-018",
    type: "plan_changed",
    orgName: "Planungs AG Bern",
    orgId: "org-planungs-be",
    user: "Jonas Jud",
    timestamp: "2026-07-19T14:00:00Z",
    meta: "Starter → Pro",
  },
  {
    id: "act-019",
    type: "org_paused",
    orgName: "DesignBau Studio",
    orgId: "org-design-bau",
    user: "Jonas Jud",
    timestamp: "2026-07-18T10:00:00Z",
  },
  {
    id: "act-020",
    type: "org_created",
    orgName: "Planungs AG Bern",
    orgId: "org-planungs-be",
    user: "Jonas Jud",
    timestamp: "2026-07-14T09:00:00Z",
  },
];

export const SYSTEM_SERVICES: SystemService[] = [
  { name: "KI-Analyse",       key: "ai",      status: "online",   latencyMs: 842  },
  { name: "Datenbank",        key: "db",      status: "online",   latencyMs: 12   },
  { name: "Storage",          key: "storage", status: "online",   latencyMs: 38   },
  { name: "Authentifizierung",key: "auth",    status: "online",   latencyMs: 67   },
  { name: "OCR / Dokumente",  key: "ocr",     status: "degraded", latencyMs: 2140, note: "Erhöhte Latenz" },
  { name: "E-Mail",           key: "email",   status: "online",   latencyMs: 145  },
  { name: "Hosting (Vercel)", key: "hosting", status: "online",   latencyMs: 22   },
];
