import type { Organization, Activity, SystemService } from "./types";

export const MOCK_ORGS: Organization[] = [
  {
    id: "tracebuild-default",
    name: "TraceBuild",
    planTier: "enterprise",
    status: "active",
    createdAt: "2025-01-15T08:00:00Z",
    isDefault: true,
    description: "Interne TraceBuild-Organisation für Entwicklung und Testing",
    owner: "Admin",
    ownerEmail: "admin@tracebuild.ch",
    userCount: 4,
    projectCount: 12,
    analyseCount: 247,
    storageGB: 5.1,
    monthlyBudget: 150,
  },
  {
    id: "hochbauamt-zh",
    name: "Hochbauamt Kanton ZH",
    planTier: "enterprise",
    status: "active",
    createdAt: "2025-03-01T09:00:00Z",
    description: "Kantonales Hochbauamt Zürich – Planprüfung und Normenkontrolle",
    owner: "Thomas Meier",
    ownerEmail: "t.meier@hochbauamt-zh.ch",
    userCount: 18,
    projectCount: 34,
    analyseCount: 521,
    storageGB: 18.2,
    monthlyBudget: 500,
  },
  {
    id: "muller-architekten",
    name: "Müller Architekten AG",
    planTier: "pro",
    status: "active",
    createdAt: "2025-04-12T10:30:00Z",
    description: "Architekturbüro in Zürich, spezialisiert auf Wohnbauten",
    owner: "Sandra Müller",
    ownerEmail: "s.mueller@mueller-architekten.ch",
    userCount: 7,
    projectCount: 19,
    analyseCount: 134,
    storageGB: 3.5,
    monthlyBudget: 200,
  },
  {
    id: "planungs-bern",
    name: "Planungs AG Bern",
    planTier: "pro",
    status: "active",
    createdAt: "2025-05-20T14:00:00Z",
    description: "Generalplaner für Infrastrukturprojekte im Kanton Bern",
    owner: "Lukas Steiner",
    ownerEmail: "l.steiner@planungs-ag.ch",
    userCount: 5,
    projectCount: 8,
    analyseCount: 72,
    storageGB: 2.8,
    monthlyBudget: 150,
  },
  {
    id: "designbau-studio",
    name: "DesignBau Studio",
    planTier: "starter",
    status: "active",
    createdAt: "2025-06-08T11:00:00Z",
    description: "Kleines Studio für Innenarchitektur und Umbau",
    owner: "Anja Roth",
    ownerEmail: "a.roth@designbau.ch",
    userCount: 2,
    projectCount: 4,
    analyseCount: 28,
    storageGB: 0.6,
    monthlyBudget: 50,
  },
  {
    id: "architektur-kollektiv",
    name: "Architektur Kollektiv",
    planTier: "starter",
    status: "closed",
    createdAt: "2025-02-28T09:00:00Z",
    description: "Ehemaliges Kollektiv – Konto geschlossen",
    owner: "Marc Weber",
    ownerEmail: "m.weber@archkollektiv.ch",
    userCount: 3,
    projectCount: 2,
    analyseCount: 11,
    storageGB: 0.3,
    monthlyBudget: 50,
  },
];

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  d.setHours(Math.floor(Math.random() * 8) + 8, Math.floor(Math.random() * 59));
  return d.toISOString();
}

export const MOCK_ACTIVITIES: Activity[] = [
  { id: "act-001", type: "org_opened",        orgName: "TraceBuild",            orgId: "tracebuild-default", user: "admin@tracebuild.ch",      timestamp: daysAgo(0),  meta: undefined },
  { id: "act-002", type: "analyse_completed", orgName: "Hochbauamt Kanton ZH",  orgId: "hochbauamt-zh",      user: "t.meier@hochbauamt-zh.ch", timestamp: daysAgo(0),  meta: "Grundriss EG, 48 Seiten" },
  { id: "act-003", type: "plan_uploaded",     orgName: "Müller Architekten AG", orgId: "muller-architekten", user: "s.mueller@mueller-architekten.ch", timestamp: daysAgo(0), meta: "Schnittplan A3.pdf" },
  { id: "act-004", type: "analyse_started",   orgName: "Planungs AG Bern",      orgId: "planungs-bern",      user: "l.steiner@planungs-ag.ch", timestamp: daysAgo(1),  meta: "Aussenansicht Süd" },
  { id: "act-005", type: "report_created",    orgName: "Hochbauamt Kanton ZH",  orgId: "hochbauamt-zh",      user: "t.meier@hochbauamt-zh.ch", timestamp: daysAgo(1),  meta: "PDF-Bericht Juli 2026" },
  { id: "act-006", type: "user_invited",      orgName: "Müller Architekten AG", orgId: "muller-architekten", user: "s.mueller@mueller-architekten.ch", timestamp: daysAgo(1), meta: "p.hofer@mueller-architekten.ch" },
  { id: "act-007", type: "project_created",   orgName: "DesignBau Studio",      orgId: "designbau-studio",   user: "a.roth@designbau.ch",      timestamp: daysAgo(2),  meta: "Umbau Wohnung Zürich Seefeld" },
  { id: "act-008", type: "org_edited",        orgName: "Planungs AG Bern",      orgId: "planungs-bern",      user: "admin@tracebuild.ch",      timestamp: daysAgo(2),  meta: "Monatsbudget angepasst" },
  { id: "act-009", type: "plan_changed",      orgName: "DesignBau Studio",      orgId: "designbau-studio",   user: "admin@tracebuild.ch",      timestamp: daysAgo(3),  meta: "starter → pro" },
  { id: "act-010", type: "analyse_completed", orgName: "Müller Architekten AG", orgId: "muller-architekten", user: "s.mueller@mueller-architekten.ch", timestamp: daysAgo(3), meta: "Grundriss OG 1+2" },
  { id: "act-011", type: "cost_limit_reached",orgName: "Hochbauamt Kanton ZH",  orgId: "hochbauamt-zh",      user: undefined,                  timestamp: daysAgo(4),  meta: "90 % des Monatsbudgets erreicht" },
  { id: "act-012", type: "org_created",       orgName: "DesignBau Studio",      orgId: "designbau-studio",   user: "admin@tracebuild.ch",      timestamp: daysAgo(5),  meta: undefined },
  { id: "act-013", type: "org_paused",        orgName: "Architektur Kollektiv", orgId: "architektur-kollektiv", user: "admin@tracebuild.ch",   timestamp: daysAgo(6),  meta: undefined },
  { id: "act-014", type: "org_closed",        orgName: "Architektur Kollektiv", orgId: "architektur-kollektiv", user: "admin@tracebuild.ch",   timestamp: daysAgo(7),  meta: undefined },
  { id: "act-015", type: "plan_uploaded",     orgName: "Hochbauamt Kanton ZH",  orgId: "hochbauamt-zh",      user: "t.meier@hochbauamt-zh.ch", timestamp: daysAgo(8),  meta: "Lageplan Areal Zürich Nord" },
  { id: "act-016", type: "analyse_started",   orgName: "Hochbauamt Kanton ZH",  orgId: "hochbauamt-zh",      user: "t.meier@hochbauamt-zh.ch", timestamp: daysAgo(9),  meta: "Lageplan Areal Zürich Nord" },
  { id: "act-017", type: "project_created",   orgName: "Planungs AG Bern",      orgId: "planungs-bern",      user: "l.steiner@planungs-ag.ch", timestamp: daysAgo(10), meta: "Brücke A6 Sanierung Bern" },
  { id: "act-018", type: "user_invited",      orgName: "Hochbauamt Kanton ZH",  orgId: "hochbauamt-zh",      user: "t.meier@hochbauamt-zh.ch", timestamp: daysAgo(11), meta: "r.kraft@hochbauamt-zh.ch" },
  { id: "act-019", type: "org_archived",      orgName: "Architektur Kollektiv", orgId: "architektur-kollektiv", user: "admin@tracebuild.ch",  timestamp: daysAgo(12), meta: undefined },
  { id: "act-020", type: "org_opened",        orgName: "TraceBuild",            orgId: "tracebuild-default", user: "admin@tracebuild.ch",      timestamp: daysAgo(14), meta: undefined },
];

export const SYSTEM_SERVICES: SystemService[] = [
  { name: "KI-Analyse",   key: "ai",      status: "online",   latencyMs: 340  },
  { name: "Datenbank",    key: "db",      status: "online",   latencyMs: 12   },
  { name: "Storage",      key: "storage", status: "online",   latencyMs: 28   },
  { name: "Auth",         key: "auth",    status: "online",   latencyMs: 18   },
  { name: "OCR-Dienst",   key: "ocr",     status: "degraded", latencyMs: 2140, note: "Erhöhte Latenz seit 14:32" },
  { name: "E-Mail",       key: "email",   status: "online",   latencyMs: 95   },
  { name: "Hosting",      key: "hosting", status: "online",   latencyMs: 8    },
];
